# Generated by Django 4.0.4 on 2022-05-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0002_organization_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='category example', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(default='date', max_length=1000),
            preserve_default=False,
        ),
    ]
