# Generated by Django 4.0.4 on 2022-05-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0003_event_category_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='orgs',
            field=models.ManyToManyField(to='causes.organization'),
        ),
    ]
