# Generated by Django 4.0.4 on 2022-05-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0004_volunteer_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='events',
            field=models.ManyToManyField(to='causes.event'),
        ),
    ]
