# Generated by Django 4.0.4 on 2022-05-25 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0005_volunteer_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=1000)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causes.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causes.organization')),
            ],
        ),
    ]
