# Generated by Django 4.0.4 on 2022-05-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0007_alter_task_event_alter_task_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='tasks',
            field=models.ManyToManyField(to='causes.task'),
        ),
    ]
