# Generated by Django 4.0.4 on 2022-06-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0005_alter_event_date'),
        ('causes', '0008_volunteer_tasks'),
    ]

    operations = [
    ]
