# Generated by Django 4.0.4 on 2022-06-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0011_alter_event_options_alter_event_date_alter_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='organization',
        ),
    ]
