# Generated by Django 4.0.4 on 2022-06-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0012_remove_task_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
    ]
