# Generated by Django 4.0.4 on 2022-06-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0013_remove_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
