# Generated by Django 4.0.4 on 2022-06-08 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0014_alter_task_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date']},
        ),
    ]
