export const COLORS = {
    navpurple: '#2a1e75',
    // lightred: '#FCF0F2',
    lightred: '#E7CCE7',
    lightaqua: '#CAE8F2',
    lightgreen: '#D2FAD5',
    lightpink: '#FAD2F7',
    lightyellow: '#FDF9DB',
    lightpurple: '#C4CBFD',
    lightblue: '#CCEBFD',
    lightorange: '#FDDFCC',
    red: '#FAB2C0',
    aqua: '#B2FAEC',
    green: '#AAF5B0',
    pink: '#F5AAF0',
    yellow: '#FBF0A1',
    purple: '#A1ACFB',
    blue: '#9AD7FC',
    orange: '#FCBF9A',
    // darkred: '#D82747',
    darkred: '#BC71BD',
    darkaqua: '#27D8B8',
    darkgreen: '#54EC5F',
    darkpink: '#EC54E0',
    darkyellow: '#F8E34F',
    darkpurple: '#4F64F8',
    darkblue: '#45B5F9',
    // darkorange: '#F98945',
    darkorange: '#CF4D11',
};